from . import res_partner
from . import sale_order
from . import sms_message
from . import sale_order_line
from . import bulk_order
from . import sale_holiday
from . import QueuePublisher
from . import split_models
from . import loyalty_program
from . import sale_loyality_config
from . import sale_order_loyality
